### ISSUE TITLE
Feature detection vs browser sniffing

### ISSUE THREAD

**Issue by kaelig** [louisremi/jquery.backgroundSize.js#1]
Salut,

Que penses-tu de détecter l'applicabilité du script selon les capacités du navigateur plutôt que via un commentaire conditionnel.

Je veux bien sûr parler de la détection via Modernizr + chargement avec YepNope.js.

PS : Bravo pour la qualité de ton code.

**Comment by louisremi** [comment]
Salut Kaelig,

Il y a au moins trois options pour charger ce script:
- si ton site utilise déjà Modernizr + YepNope, tu peux tout à fait ajouter une condition pour charger ce script,
- tu peux utiliser un commentaire conditionnel comme préconisé dans le README
- tu peux charger le script sans commentaire conditionnel et son contenu ne sera exécuté que dans IE (il y a un test de feature detection embarqué)

Le commentaire conditionnel est la méthode privilégiée parce qu'elle évite de rajouter des dépendances (Modernizr et YepNope) et qu'elle est considérée comme sûre (utilisée dans HTML5Boilerplate par exemple).

Et merci pour ton intérêt :-)

**Comment by kaelig** [comment]
Merci pour ta réponse.

J'imagine que le script chargé seul (sans commentaires conditionnels) sera aussi lancé sous Firefox < 3.6 ?

**Comment by louisremi** [comment]
Oui, j'ai pas vraiment pensé à ce cas parce que les parts de marché de Firefox <3.6 sont négligeables, mais à priori ça devrait marcher.
