### ISSUE TITLE
with fancybox

### ISSUE THREAD

**Issue by Spica2** [louisremi/jquery.backgroundSize.js#2]
I consider using your script with fancybox. As expected I have some problems to get it run.

So, I have the lightbox with this object
`<div class="fancybox-image" style="background-image:url({href});background-size: cover;background-position:50% 50%;background-repeat:no-repeat;height:100%;width:100%;"></div>`

My problem is to point your script to the .fancybox-image. e.g. I tried to put it in a resize
`$(window).resize(function() {
              $('.fancybox-image').css( "background-size", "cover" );
              $.refreshBackgroundDimensions($('.fancybox-image'));
            });`

I am not sure, if the refresh can be called like this? (later I want to put it in a callback for the lightboxanimation)
And do I need to set the background-size by jquery or is it ok just by setting it in the style?

**Comment by louisremi** [comment]
Hi @Spica2,
What is it your are trying to achieve? What is fancybox? A slideshow plugin?
Have you got an example working in other browsers?

Regards,
Louis-Rémi

**Comment by Spica2** [comment]
fancybox is indeed a slideshow plugin based on jquery, works with lightbox principles. I made it displaying imgs fullsized with the backgroundsize cover of ccs3. for ie8 I wanted to use your script. But it seems to conflict with fancybox – two scripts manipulating the same DOM. Maby the conflict is with different handling of the z-indexes. Manipulating the DOM for HTML-lightboxes works.

**Comment by louisremi** [comment]
I need a demo of your work and your to be able to help you.

**Comment by Spica2** [comment]
thanks for your support. Unfortunately I just have a local installation. Anyway, I decided now to try a different solution.
