### ISSUE TITLE
jQuery-injected backgrounds

### ISSUE THREAD

**Issue by ghost** [louisremi/jquery.backgroundSize.js#3]
Hi Louis, I've found this to work brilliantly but I'm having a problem when the background image is set via jQuery on pageload (randomly from a JSON-supplied list) rather than explicitly in CSS. I've tried working around this somehow using $.refreshBackgroundDimensions but with no luck.

Basically here's what I'm doing:

$.getJSON('/assets/hero.json', function(data) {
  var item = data.heroes[Math.floor(Math.random()*data.heroes.length)];
  $('#hero').css('background-image', 'url(/assets/hero/' + item.hero + ')');
});

I've tried loading the backgroundSize script after the entire document is loaded and other ways but no matter what I do I just end up with no background image being set in IE. Is there some way to make this work in my scenario?

**Comment by louisremi** [comment]
This should work out of the box. Have you got a test page somewhere?

**Comment by ghost** [comment]
Sure: http://cynium.com/bgtest/

**Comment by louisremi** [comment]
There was a very embarassing bug in the plugin, I just pushed a new version that should fix it.
Can you confirm that?

**Comment by ghost** [comment]
Works perfectly now, thanks!

**Comment by louisremi** [comment]
Thank you for taking the time to report the bug.
